version: '3.8'
services:
  urlshortener:
    image: urlshortener:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=urlshortener
      - DB_PASS=urlshortener_password
      - DB_NAME=urlshortener
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener_password
      POSTGRES_DB: urlshortener
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
